spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path= /customers/**

        - id: r2
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path= /products/**
